### PR TITLE
Fix Data Grid crashing with `Attribute "data-row-key" not found`

### PR DESCRIPTION
**Pull request by jabbapen**
* Addressed issue #1707
* Changed event.target to event.currentTarget in onRowMouseEnter
* Issue seems to be the target being the child element(dropdown) rather than the row. This isn't an issue when you hover over a cell because it has the data-row-key property but it is an issue when we hover over a dropdown.

### CODE REVIEW

**Comment by joshwooding** [comment]
Hey @jabbapen, thank you for the contribution.

We require all contributors to JPMC projects to complete our Contribution Licence Agreement (CLA). You can sign as an individual or as representing your company. You only need to do this once, and it covers all current and future projects managed under our GitHub organization.

The contribution agreement can be found here [JPMC CLA](https://github.com/jpmorganchase/.github/blob/main/jpmc-cla-20230406.md), if you could follow the instructions to complete and return via email we can get this merged.

Thanks!

**Comment by jabbapen** [comment]
Awesome! I've attached the agreement to this email. Thanks Josh.

**Comment by joshwooding** [comment]
> Awesome! I've attached the agreement to this email. Thanks Josh.

Hi @jabbapen,

Did you send the CLA to [opensource_cla@jpmchase.com](mailto:opensource_cla@jpmchase.com)?

Thanks,
Josh

**Comment by jabbapen** [comment]
Ah my apologies. I sent it to that email. Sorry for the confusion.

**Review by joshwooding — APPROVED** [review]

**Review by joshwooding — APPROVED** [review]

**Review by joshwooding — APPROVED** [review]

**Comment by joshwooding** [comment]
Thank you for your contribution @jabbapen :tada:

**Pull request merged**
