### PR TITLE
Add back custom format date picker example

### PR DESCRIPTION
**Pull request by origami-z**
Feedback from user this capability is not clear

### CODE REVIEW

**Review by joshwooding — APPROVED** [review]
@mark-tate does this change a lot in #4291 ?

**Comment by mark-tate** [comment]
I would park this..
Format is no longer a function, it's a string.

**Comment by origami-z** [comment]
> I would park this.. Format is no longer a function, it's a string.

will the new version be released very soon? This is being asked in support quite a lot

**Comment by mark-tate** [comment]
format is now a string based and implemented by adapter.. Will need to revisit this example, if it is still required?

Let's get some feedback on the Adapter based version of date-picker to see whether this example is needed.

Now things are string based and re-use the date framework's API, I wonder if we need to document recommended formats.
I added a doc that lists the currently used formats to our docs. 
@ivan-calderon worth reviewing, see the LocalizationProvider which also documents adapters.

In theory, you could also extend the adapter and implement your own custom formatting, if there was an issue with the current formatting approach.

**Pull request closed without merging**
