### PR TITLE
Scope floating ui portal

### PR DESCRIPTION
**Pull request by origami-z**
This should solve the problem where users using mixed density and portal launch mess up the whole UI

### CODE REVIEW

**Comment by joshwooding** [comment]
@origami-z Is there anything blocking this PR?

**Comment by origami-z** [comment]
> @origami-z Is there anything blocking this PR?

no, i wanted to see chromatic or snapshot test

**Comment by joshwooding** [comment]
@origami-z Are you happy for this to be merged in?

**Review by joshwooding — APPROVED** [review]

**Comment by origami-z** [comment]
> @origami-z Are you happy for this to be merged in?

tested with `0.0.0-snapshot-20241212132702`, working locally

**Comment by origami-z** [comment]
@ImmanuelBaskaran do you think this will impact desktop?

**Comment by ImmanuelBaskaran** [comment]
This does not affect desktop, we provide our own floating portal component.

**Review by Fercas123 — APPROVED** [review]

**Review by Fercas123 — APPROVED** [review]

**Pull request merged**
