### PR TITLE
Add `PropsTablePlugin` to site

### LINKED ISSUE #1665: Figure out how to auto-generate props table on Mosaic

### PR DESCRIPTION
**Pull request by JoanaMMoreira**
Closes #1665 

Preview at https://saltdesignsystem-git-upgrade-mosaic-joshwooding.vercel.app/salt/components/button/usage

### CODE REVIEW

**Comment by james-nash** [comment]
There's an outstanding bug in the new Mosaic `PropsTablePlugin` that preventing site builds from working. Here's the errors I get when running `yarn build` on the site locally:

```
8080 [Mosaic] Source 'site#65cc371b' received first docs snapshot 0.002s after starting.
8080 Error: Error: Error: Plugin '@jpmorganchase/mosaic-plugins/PropsTablePlugin' threw an exception running `$afterSource`. See below:
8080   TypeError: Cannot read properties of undefined (reading 'props')
8080     at file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-plugins/dist/PropsTablePlugin.js:18:78
8080     at overload (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-plugins/node_modules/unist-util-visit/lib/index.js:173:16)
8080     at node (textDirective<propsTable>) (file:///Users/R700611/code/salt/salt-monorepo/node_modules/unist-util-visit-parents/lib/index.js:189:31)
8080     at node (paragraph) (file:///Users/R700611/code/salt/salt-monorepo/node_modules/unist-util-visit-parents/lib/index.js:206:79)
8080     at node (root) (file:///Users/R700611/code/salt/salt-monorepo/node_modules/unist-util-visit-parents/lib/index.js:206:79)
8080     at visitParents (file:///Users/R700611/code/salt/salt-monorepo/node_modules/unist-util-visit-parents/lib/index.js:148:35)
8080     at visit (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-plugins/node_modules/unist-util-visit/lib/index.js:165:7)
8080     at Proxy.$afterSource (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-plugins/dist/PropsTablePlugin.js:15:13)
8080     at async pluginRunner (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/plugin/pluginRunner.js:17:28)
8080     at async Proxy.<anonymous> (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/plugin/createPluginAPI.js:58:34)
8080     at Object.$afterSource (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/plugin/index.js:36:23)
8080 Error: [Mosaic] Source 'site#65cc371b' threw an exception. See below:
8080     at EventEmitter.<anonymous> (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/PullDocs.js:81:27)
8080     at Object.onceWrapper (node:events:628:26)
8080     at EventEmitter.emit (node:events:525:35)
8080     at file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/Source.js:121:57
8080     at EventEmitter.autoUnsubscribeHandler (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/WorkerSubscription.js:34:13)
8080     at EventEmitter.emit (node:events:513:28)
8080     at Object.#onError [as error] (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/WorkerSubscription.js:61:23)
8080     at ConsumerObserver.error (/Users/R700611/code/salt/salt-monorepo/node_modules/rxjs/dist/cjs/internal/Subscriber.js:124:33)
8080     at SafeSubscriber.Subscriber._error (/Users/R700611/code/salt/salt-monorepo/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
8080     at SafeSubscriber.Subscriber.error (/Users/R700611/code/salt/salt-monorepo/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
8080 Error: Error: Error: Plugin '@jpmorganchase/mosaic-plugins/PropsTablePlugin' threw an exception running `$afterSource`. See below:
8080   TypeError: Cannot read properties of undefined (reading 'props')
8080     at file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-plugins/dist/PropsTablePlugin.js:18:78
8080     at overload (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-plugins/node_modules/unist-util-visit/lib/index.js:173:16)
8080     at node (textDirective<propsTable>) (file:///Users/R700611/code/salt/salt-monorepo/node_modules/unist-util-visit-parents/lib/index.js:189:31)
8080     at node (paragraph) (file:///Users/R700611/code/salt/salt-monorepo/node_modules/unist-util-visit-parents/lib/index.js:206:79)
8080     at node (root) (file:///Users/R700611/code/salt/salt-monorepo/node_modules/unist-util-visit-parents/lib/index.js:206:79)
8080     at visitParents (file:///Users/R700611/code/salt/salt-monorepo/node_modules/unist-util-visit-parents/lib/index.js:148:35)
8080     at visit (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-plugins/node_modules/unist-util-visit/lib/index.js:165:7)
8080     at Proxy.$afterSource (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-plugins/dist/PropsTablePlugin.js:15:13)
8080     at async pluginRunner (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/plugin/pluginRunner.js:17:28)
8080     at async Proxy.<anonymous> (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/plugin/createPluginAPI.js:58:34)
8080     at Object.$afterSource (file:///Users/R700611/code/salt/salt-monorepo/node_modules/@jpmorganchase/mosaic-core/dist/plugin/index.js:36:23)
```

@lilyvc, before going on leave @JoanaMMoreira mentioned that you might be able to help investigate and fix this since you were involved in helping her make that plugin. Would you be able to help us with this? I'm happy to raise a defect in the Mosaic repo if needed.

**Comment by origami-z** [comment]
> I can take a look

what's the PR or Issue of the fix from Mosaic?

**Comment by JoanaMMoreira** [comment]
> > I can take a look
> 
> what's the PR or Issue of the fix from Mosaic?

I'll raise a PR in Mosaic :)

**Comment by JoanaMMoreira** [comment]
> > > I can take a look
> > 
> > 
> > what's the PR or Issue of the fix from Mosaic?
> 
> I'll raise a PR in Mosaic :)

https://github.com/jpmorganchase/mosaic/pull/388

**Pull request closed without merging**
