### PR TITLE
Fix height of closable pill next

### PR DESCRIPTION
**Pull request by Fercas123**
adding max-width to the close button inside pill to avoid specificity issues when styles are applied from an external wrapper

### CODE REVIEW

**Review by origami-z — COMMENTED** [review]
The change feels a little random. Is there a need to add a test or something else to show why this is needed?

**Comment by Fercas123** [comment]
> The change feels a little random. Is there a need to add a test or something else to show why this is needed?

Screenshot 2023-11-14 at 13 40 43

The issue happens when styles are applied to `.saltButton` externally (from multilineinput in this case) and override the class passed within the pill.
Multiline input applies a general style rule because it is used in all buttons inside end and start adornments

**Comment by origami-z** [comment]
> The issue happens when styles are applied to `.saltButton` externally (from multilineinput in this case) and override the class passed within the pill.

If this comes from `Button`, should there be a height CSS API exposed, and overridden in `PillNext` and adornment accordingly? Applying `max-height` feels like a last hope solution

**Review by lilyvc — APPROVED** [review]

**Comment by Fercas123** [comment]
> > The issue happens when styles are applied to `.saltButton` externally (from multilineinput in this case) and override the class passed within the pill.
> 
> If this comes from `Button`, should there be a height CSS API exposed, and overridden in `PillNext` and adornment accordingly? Applying `max-height` feels like a last hope solution

both of them use `--saltButton-height` already

**Comment by origami-z** [comment]
> both of them use `--saltButton-height` already, the thing is, even though pill uses it within a class, multiline input uses it inside `.saltMultilineInput .saltButton`, which wins the race, i could do `.saltPillNext .saltPillNext-close-button.saltButton`

Is Multiline input targeting too widely? Should it only targeting buttons within adornment?

**Comment by joshwooding** [comment]
> > both of them use `--saltButton-height` already, the thing is, even though pill uses it within a class, multiline input uses it inside `.saltMultilineInput .saltButton`, which wins the race, i could do `.saltPillNext .saltPillNext-close-button.saltButton`
> 
> Is Multiline input targeting too widely? Should it only targeting buttons within adornment?

I raised this to design last week, the overrides applied with button input adornments are broken and too restrictive. They are currently very broken and should be removed.

**Comment by Fercas123** [comment]
> > > both of them use `--saltButton-height` already, the thing is, even though pill uses it within a class, multiline input uses it inside `.saltMultilineInput .saltButton`, which wins the race, i could do `.saltPillNext .saltPillNext-close-button.saltButton`
> > 
> > 
> > Is Multiline input targeting too widely? Should it only targeting buttons within adornment?
> 
> I raised this to design last week, the overrides applied with button input adornments are broken and too restrictive. They are currently very broken and should be removed.
> 
> I don't think this change should go ahead and I think that root problem should be solved

makes sense, should we have an issue to reflect that ongoing conversation?

**Comment by Fercas123** [comment]
Closing this PR as the issue has already been raised in relation to input styles.

**Pull request closed without merging**
