### PR TITLE
[HOLD][Ag Grid Theme] Column headers are wrapping instead of ellipsis

### PR DESCRIPTION
**Pull request by alycrys**
Closes https://github.com/jpmorganchase/salt-ds/issues/2630

Introduced in https://github.com/jpmorganchase/salt-ds/pull/2189 while fixing bugs https://github.com/jpmorganchase/salt-ds/issues/2185

### CODE REVIEW

**Review by origami-z — COMMENTED** [review]
Wrapped header is needed with specific configuration, the story demos the capability. 
https://blog.ag-grid.com/wrapping-column-header-text/

**Comment by alycrys** [comment]
> Wrapped header is needed with specific configuration, the story demos the capability. https://blog.ag-grid.com/wrapping-column-header-text/

If this was a new feature, then it should have been signaled as such. This seems to be a bug to both MTK and @bhoppers2008 .

**Comment by origami-z** [comment]
What does MTK expects when auto height is turned on for a header? I'd assume auto height is only needed when multi-line header is needed

**Comment by libertymayc** [comment]
this was originally requested by MTK, surprised to hear its now being seen as a bug

**Pull request closed without merging**
