### PR TITLE
Make easier to hide icon in external links

### PR DESCRIPTION
**Pull request by libertymayc**
Make easier to hide icon in external links by changing types

### CODE REVIEW

**Review by joshwooding — APPROVED** [review]

**Review by joshwooding — APPROVED** [review]
Looks good

**Review by ImmanuelBaskaran — DISMISSED** [review]

**Comment by alycrys** [comment]
When we refactored Link it was agreed by design (along with Stella) that the icon on external links should always be visible. I'm curious what's the reason for this change

**Comment by libertymayc** [comment]
> When we refactored Link it was agreed by design (along with Stella) that the icon on external links should always be visible. I'm curious what's the reason for this change

its for wrapping components like Card in Link

**Comment by joshwooding** [comment]
@alycrys @libertymayc I think we should have this functionality. We should either not document it on the Link page or add a warning that this is only needed when you wrap a component in the Link

**Review by ImmanuelBaskaran — APPROVED** [review]

**Review by alycrys — APPROVED** [review]

**Pull request merged**
