### PR TITLE
Update Tooltip to have a default, non-status state

### LINKED ISSUE #3091: Allow Tooltip to not have a status
### Area

UI Components

### The problem

Tooltip currently needs a status present. This does not align with Dialog or other component with statuses.

### The solution

Allow Tooltip to not require a status, swapping the info status colours with containerable.

### Alternatives and examples

.

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

### PR DESCRIPTION
**Pull request by libertymayc**
closes #3091
Appreciate I may have jumped ahead with this one if we aren't sure about it, and design input needed
Feel free to draft

### CODE REVIEW

**Comment by joshwooding** [comment]
> closes #3091 Appreciate I may have jumped ahead with this one if we aren't sure about it, and design input needed Feel free to draft

You have a bit :P Design has come up with a visual, I think they need to share it and get feedback. I'll move it to draft temporarily until that is done.

We also won't be able to do this as a major change. It will be defined as a bug fix.

**Comment by bhoppers2008** [comment]
@libertymayc you can find what you need [here](https://www.figma.com/file/2MkAG823JHbWgCffEU9xnm/Overlayables-proposition?type=design&node-id=0%3A228&mode=design&t=dx18jkkkJBOzAYH6-1). The same behaviour extends to toast as well. Dialog already does this.

**Comment by joshwooding** [comment]
> thanks @bhoppers2008! re: above proposition, @joshwooding did we want to also add the custom icon now? if not, i'll just hide icon when no status present

That's being handled elsewhere, hiding it for now is fine

**Comment by libertymayc** [comment]
cool, styles were as design so I've updated the changeset to be a patch fix; pr should be good to go when we want to move out of draft @joshwooding

**Review by joshwooding — APPROVED** [review]

**Review by joshwooding — APPROVED** [review]

**Review by Fercas123 — APPROVED** [review]

**Pull request merged**
