### PR TITLE
AG grid theme changes

### PR DESCRIPTION
**Pull request by libertymayc**
Replaced borders (which was a bit hacked - had to give transparent border to avoid content shifting) to outlines

### CODE REVIEW

**Review by origami-z — COMMENTED** [review]
remove commented code + changeset

**Comment by libertymayc** [comment]
> remove commented code + changeset

whoops sorry, been a while since i did this stuff and forgot to check - done

**Comment by origami-z** [comment]
Some visual regression  between cell and header vertical alignment

**Review by lilyvc — DISMISSED** [review]

**Comment by libertymayc** [comment]
> Some visual regression between cell and header vertical alignment

I believe this is ok, from what I see its the 2px border on cells have been removed so everything is slightly shifted relatively to not needing that anymore

**Review by origami-z — APPROVED** [review]

**Review by alycrys — APPROVED** [review]

**Pull request merged**
