### PR TITLE
Deprecate `--salt-zIndex-docked`

### LINKED ISSUE #2183: Remove --salt-zIndex-docked from Z-Index Foundation
Following a discussion with @origami-z @bhoppers2008 @joshwooding we believe Docked is no longer needed as it relates to a legacy feature within UITK and isn't something we're planning on recreating within Salt (relates to the Drawer component). 

```[tasklist]
### Tasks
- [x] Remove Docked from Figma doc
- [ ] Remove Docked from Z-Index Foundation page on website
- [ ] Deprecate Docked token from code
- [ ] Add to v2 removal list
```

### PR DESCRIPTION
**Pull request by joshwooding**
Closes #2183

### CODE REVIEW

**Review by pseys — APPROVED** [review]

**Review by origami-z — APPROVED** [review]
Just realized no foundation stuff is documented on site/storybook?

**Comment by libertymayc** [comment]
I thought we weren't making dev changes that have no direct need/impact now?

**Comment by joshwooding** [comment]
> Just realized no foundation stuff is documented on site/storybook?

Some stuff is documented on the site. The z-index is being added

**Comment by joshwooding** [comment]
> I thought we weren't making dev changes that have no direct need/impact now?

This is a minor change related to a conversation we're having today

**Pull request merged**
